- name: Ensure {{name}} log directory exists
  include: mkdir.yml dir=/var/log/{{name}} owner={{log_owner|default(ansible_ssh_user)}} group=admin
  become: yes
  changed_when: false

- name: Copy logrotate config
  template: src=templates/logrotate.conf.j2 dest=/etc/logrotate.d/{{name}}
  become: yes