- name: Check if path contains our path
  shell: ". /etc/environment && echo $PATH | grep {{path}}"
  register: path_check
  ignore_errors: true
  changed_when: false

- name: Add {{name|default(path)}} to path
  replace: dest=/etc/environment regexp='^(export )?PATH="(.*)"$' replace="PATH=\"\2:{{path}}\""
  become: yes
  when: path_check|failed
  register: replace_path

- name: Reboot to force uptake of new env
  include: reboot.yml
  when: replace_path|changed
