- name: Create directory for service "{{service_name}}"
  include: mkdir.yml dir="{{item}}"
  with_items:
    - "/etc/systemd/system/{{service_name}}.d/"
  become: yes

- name: Copy limits.conf for service "{{service_name}}"
  template: src=systemd_open_files_limit.conf.j2 dest="/etc/systemd/system/{{service_name}}.d/limits.conf" owner={{ansible_ssh_user}} group=admin mode=0644
  become: yes
  when: "{{service_max_open_files is defined}}"
  register: limits

- name: Reload systemd daemons
  command: systemctl daemon-reload
  become: yes
  when: limits|changed

- name: Restart service "{{service_name}}"
  service: name="{{service_name}}" state=restarted
  become: yes
  when: restart is defined and restart